version: '3'
services:
  sync-from-the-institutions-to-auth0-organizations:
    image: 'node:18-alpine'
    container_name: sync-from-the-institutions-to-auth0-organizations
    working_dir: /app
    restart: unless-stopped
    env_file: .env
    volumes:
      - './:/app'
    command: npm run sync
